# Generated by Django 4.1.6 on 2023-02-13 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='score',
            new_name='rating',
        ),
    ]
