# Generated by Django 4.1.6 on 2023-02-14 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_place_user_alter_place_notes_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='placeType',
            field=models.TextField(choices=[('R', 'restaurant'), ('C', 'cafe'), ('B', 'bar'), ('D', 'dessert')], default='R'),
            preserve_default=False,
        ),
    ]
