# Generated by Django 4.1.6 on 2023-02-14 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_place_placetype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='placeType',
            new_name='place_type',
        ),
    ]
