# Generated by Django 4.1.6 on 2023-02-14 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_rename_placetype_place_place_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='status',
            field=models.CharField(choices=[('B', 'Been'), ('H', 'Have not been')], default='B', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='place',
            name='notes',
            field=models.TextField(max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='rating',
            field=models.IntegerField(choices=[(0, ''), (1, '⭐️'), (2, '⭐️⭐️'), (3, '⭐️⭐️⭐️'), (4, '⭐️⭐️⭐️⭐️'), (5, '⭐️⭐️⭐️⭐️⭐️')], null=True),
        ),
    ]
